---
changelog:
  -
    changes:
      -
        text: "Update quickstart examples."
        type: improvement
    date: 2020-12-21
    version: v2.1.0
  - changes:
      - text: 'second public version'
        type: feature
    date: 2019-09-09
    version: v2.0.0-beta.1
files:
  - dist/pubnub-react.esm.js
name: pubnub-react
schema: 1
scm: github.com/pubnub/react
version: 'v2.1.0'
